const express = require("express");
const router = express.Router();
const AdminController = require("./admin.controller");

router.get('/user', AdminController.get);
router.get('/searchuser/:role', AdminController.searchUser);
router.post('/createsubjects', AdminController.createSubjectSet);
router.get('/getsubjects', AdminController.getSubjects);
router.post('/createsubject', AdminController.createSubject);
router.get('/getsubject', AdminController.getSubject);
router.post('/createtern', AdminController.createTern);
router.get('/gettern', AdminController.getTern);
router.put('/starttern/:id', AdminController.startTern);
router.put('/endtern/:id', AdminController.endTern);
router.post('/editprofile', AdminController.editProfile);
router.get('/getprofile/:id', AdminController.getProfile);
router.post('/createsession', AdminController.createSession);
router.get('/getsession', AdminController.getSession);
router.put('/startsession/:id', AdminController.startSession);
router.put('/endsession/:id', AdminController.endSession);
router.delete('/deletesession/:id', AdminController.deleteSession);
router.get('/test', AdminController.test);
router.post('/createclass', AdminController.createClass);
router.get('/getclass', AdminController.getClass);
router.delete('/deleteclass/:id', AdminController.deleteClass);
router.post('/assignment/:id/:idtern/:idclass', AdminController.assignment);
router.get('/getlecturer', AdminController.getLecturer);
router.get('/listclassoflec/:id/:idtern', AdminController.getlistclassofLecturer);
router.post('/setpoint', AdminController.setPointOfStudent);
router.get('/getstudents/:code', AdminController.getStudents);
router.post('/editstudent', AdminController.editStudents);
router.get('/updatestudent', AdminController.updateStudents);
module.exports = router;